# .github/workflows/deploy.yml
name: Deploy LesCracks

on:
  push:
    branches: [ master ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Déploiement sur le serveur
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.COTANBO_HOST }}
          username: root
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /root/lescracks
            
            git pull origin master
            
            docker compose down --remove-orphans || true
            docker compose up --build -d
            
            docker image prune -f
            
            echo "Déployé avec succès ! $(date)"